dist: bionic

language: node_js

node_js:
  - "node"

branches:
  only:
    - master
    - /^\d.\d+$/

install:
  - composer install
  - yarn install

before_script:
  - yarn global add grunt-cli
  - cp grunt.json.dist grunt.json

script:
  - grunt build

notifications:
  email: false
  slack:
    rooms:
      - secure: "NZUAr7xcDdzZxru/GsH/zwmLOC3ERSMd2J4y51bjgv6Db41O40E5U9AZMjoTWfOz5qRjC/DZPYstZyZAdH2QufKj1Jmf+z5X5ukJA7isAi/HIycjqJrL9VRlCjPx4T4IIwOK2zhezK82ugNPJucQ5mQoyKrFu4mfgtml7AH7XL6Hu8lkoqGZw+cpkkFCeYJZkLmAcF5EJU9onER/KLxOcM9/bddhCS9iYuyZYWwTJ6qzPb/k5g5PzXl9LiUYGOWlPJyoTM2yre8rv1wKCMVfhEO/c6oGs9sEncfbXXEnoL5I8LTZabcuz1ax6wzNI7K4P5Vn1BElVEnSbRu/m7Vc4njnANnjHAufNPM3mp4gsfsvL98pojSQdNYsQBNguo7opo5x/GMqcfLK7G7Xto19WdZuv97qolqcIhVzERs9HK23SX/lQxUClUIA1atXzo/aUr1JpXcAMhhhXo7Oooh6BFcWrAjRCrdjSo3kAkDLvUXtP3LIg+RKBx3NwHS1t9a8C4jThDZ+uSS1vt9Z5+EqI5Wo7Jf9v057OQjYD8wpWCTHjzYbWuelWwNSkAItQRB6r7IUe89VnyoVYqMYJhjy5WHHrWZpjWeYlrzvAX5ofU/qUSDIsiwTcWGK0FQcIm0H/EXz+/uR0EKJNOUWqTOX3o3r3TGhFy+9PSAmda34m7U="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
