assets:
    packages:
        nglayouts_app_css:
            base_path: '/bundles/netgenlayoutsui/css'
            version: '%netgen_layouts.app.asset_version%'
            version_format: '%%s?%%s'
        nglayouts_app_js:
            base_path: '/bundles/netgenlayoutsui/js'
            version: '%netgen_layouts.app.asset_version%'
            version_format: '%%s?%%s'
        nglayouts_app_vendor:
            base_path: '/bundles/netgenlayoutsui/vendor'
            version: '%netgen_layouts.app.asset_version%'
            version_format: '%%s?%%s'
        nglayouts_app:
            base_path: '/bundles/netgenlayoutsui'
            version: '%netgen_layouts.app.asset_version%'
            version_format: '%%s?%%s'
