assets:
    packages:
        ngbm_app_css:
            base_path: '/bundles/netgenlayoutsui/css'
            version: '%ngbm_app.asset.version%'
            version_format: '%%s?%%s'
        ngbm_app_js:
            base_path: '/bundles/netgenlayoutsui/js'
            version: '%ngbm_app.asset.version%'
            version_format: '%%s?%%s'
        ngbm_app_vendor:
            base_path: '/bundles/netgenlayoutsui/vendor'
            version: '%ngbm_app.asset.version%'
            version_format: '%%s?%%s'
        ngbm_app:
            base_path: '/bundles/netgenlayoutsui'
            version: '%ngbm_app.asset.version%'
            version_format: '%%s?%%s'
